testng_hw
RuslanBinyatov/AQA21onl pull request #1
Opened 2023-06-23 20:52 UTC by RuslanBinyatov

2023-06-26 14:54 UTC, wildpioneer requested changes

2023-06-26 14:54 UTC, wildpioneer commented on src/main/java/Calculator.java
> +        if (b==0) {
Это конечно хитрый ход - но в условии домашнего задания об этом ничего не говорилось

2023-06-26 14:54 UTC, wildpioneer commented on src/test/java/CalcTestHW.java
> +    @Test (dataProvider = "Data for Div Double test", dataProviderClass = StaticProviderDoubleHW.class)
Отсутствуют тесты на:
1) Parameters
2) retryAnalizer
3) Double.Nan, Double.NEGATIVE_INFINITY, Double.POSITIVE_INFINITY

2023-07-23 11:35 UTC, wildpioneer commented
Будешь ли ты исправлять?

2023-07-23 11:51 UTC, RuslanBinyatov commented on src/main/java/Calculator.java
> +        if (b==0) {
Убрал хитрый ход)

2023-07-23 11:56 UTC, RuslanBinyatov commented on src/test/java/CalcTestHW.java
> +    @Test (dataProvider = "Data for Div Double test", dataProviderClass = StaticProviderDoubleHW.class)
Оптимизировал и добавил тесты

2023-07-23 11:57 UTC, RuslanBinyatov commented
Да, исправил

2023-08-01 19:26 UTC, wildpioneer commented
Проверено

2023-08-01 19:26 UTC, closed without merging