selenium_wd_hw
RuslanBinyatov/AQA21onl pull request #2
Opened 2023-06-29 16:20 UTC by RuslanBinyatov

2023-07-03 19:50 UTC, wildpioneer requested changes

2023-07-03 19:50 UTC, wildpioneer commented on src/test/java/SmokeTestHW.java
> +        Assert.assertEquals(driver.findElement(By.id("floor_cable_power")).getText(), "67");
Тест падает:
![2023-07-03_21-48-50](https://github.com/RuslanBinyatov/AQA21onl/assets/8968693/a86c8bec-5ddf-4909-b2e3-6f9757ef2b69)

2023-07-04 10:03 UTC, RuslanBinyatov commented on src/test/java/SmokeTestHW.java
> +        Assert.assertEquals(driver.findElement(By.id("floor_cable_power")).getText(), "67");
Исправил свою ошибку - тест больше не падает.
Добавил sleep в шаги для лучшей визуализации.
Посмотрите, пожалуйста.

2023-07-10 06:20 UTC, wildpioneer commented
Проверено

2023-07-10 06:20 UTC, closed without merging