pageObject_hw
RuslanBinyatov/AQA21onl pull request #4
Opened 2023-07-22 22:42 UTC by RuslanBinyatov

2023-07-23 11:43 UTC, wildpioneer requested changes

2023-07-23 11:43 UTC, wildpioneer commented on Readme.md
> +13. нажать кнопку "Back Home"
В тесте отсутствует проверка успешного заказа. Переход на последнюю страницу не гарантирует, что заказ выполнен успешно.

2023-07-23 11:43 UTC, wildpioneer commented on src/test/java/baseEntities/BasePageHW.java
> +    public BasePageHW(WebDriver driver) {
Нет необходимости переименовывать классы с добавление HW - ведь в бранче нет больше иных классов

2023-07-23 12:32 UTC, RuslanBinyatov commented on Readme.md
> +13. нажать кнопку "Back Home"
Убрал лишний (последний) шаг;
Добавил ожидаемый результат: отображается надпись "Thank you for your order!"

2023-07-23 12:34 UTC, RuslanBinyatov commented on src/test/java/baseEntities/BasePageHW.java
> +    public BasePageHW(WebDriver driver) {
Это я больше для себя добавляю (мне так удобнее различать домашнюю и классную работу)
Переименовать (убрать HW)?

2023-07-23 13:10 UTC, RuslanBinyatov commented on src/test/java/baseEntities/BasePageHW.java
> +    public BasePageHW(WebDriver driver) {
Дополнительно добавил:
в pages:
private final By completeHeaderLocator = By.xpath("//h2[contains(@class, 'complete-header') " +
            "and contains(text(), 'Thank you for your order!')]");
в steps:
public CheckoutCompletePageHW completeHeaderIsDisplayed() {
        checkoutCompletePageHW.getCompleteHeader().isDisplayed();
        return checkoutCompletePageHW;
    }
в tests:
Assert.assertTrue(checkoutCompleteStepHW.completeHeaderIsDisplayed().isPageOpened());

2023-08-01 19:22 UTC, wildpioneer commented
Проверено

2023-08-01 19:22 UTC, closed without merging