advancedActions_hw
RuslanBinyatov/AQA21onl pull request #5
Opened 2023-07-25 18:23 UTC by RuslanBinyatov

2023-08-01 19:26 UTC, wildpioneer requested changes

2023-08-01 19:26 UTC, wildpioneer commented on src/test/java/tests/DynamicControlsTestHW.java
> +                (By.xpath("//*[@id=\"checkbox-example\"]/button"));
А почему не css?? было бы "#checkbox-example button"

2023-08-01 19:26 UTC, wildpioneer commented on src/test/java/tests/DynamicControlsTestHW.java
> +        WebElement input = waitService.waitForExists(By.xpath("//*[@id=\"input-example\"]/input"));
Общее замечание по локаторам - 

1. это заменить слеш и " на ' 
2. использовать что-то проще в виде css

2023-08-01 19:26 UTC, wildpioneer commented on src/test/java/tests/FileUploadTestHW.java
> +        fileUploadElement.sendKeys(pathToFile.substring(1,pathToFile.length()));
На будущее - учитывать, что тесты пишуться под разные ОС - следовательно пути будут разные и данный подход не подходить для Linux/Mac

2023-08-03 16:56 UTC, RuslanBinyatov commented on src/test/java/tests/DynamicControlsTestHW.java
> +                (By.xpath("//*[@id=\"checkbox-example\"]/button"));
Да, согласен, css читабельнее выглядит
Исправил

2023-08-03 16:57 UTC, RuslanBinyatov commented on src/test/java/tests/DynamicControlsTestHW.java
> +        WebElement input = waitService.waitForExists(By.xpath("//*[@id=\"input-example\"]/input"));
Исправил на более простые выражения

2023-08-03 17:15 UTC, RuslanBinyatov commented on src/test/java/tests/FileUploadTestHW.java
> +        fileUploadElement.sendKeys(pathToFile.substring(1,pathToFile.length()));
Понял, спасибо!

2023-08-07 13:17 UTC, wildpioneer commented
Проверено

2023-08-07 13:17 UTC, closed without merging